apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  namespace: icgroup
  labels:
    app: odoo
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: odoo
        ports:
        - name: odoo
          containerPort: 8069
        env:
        - name: USER
          value: m2iformation
        - name: HOST
          value: postgres
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo
              key: PASSWORD
        volumeMounts:
        - name: odoo-config
          mountPath: /etc/odoo
        - name: odoo-data
          mountPath: /var/lib/odoo
        - name: odoo-addons
          mountPath: /mnt/extra-addons
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
      volumes:
      - name: odoo-config
        hostPath:
          path: /data_docker/config
      - name: odoo-addons
        hostPath:
          path: /data_docker/addons
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-pvc
