apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-webapp
  namespace: icgroup
  labels:
    app: ic-webapp
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
      - name: ic-webapp
        image: cdobe01/ic-webapp:v1.0
        env:
        - name: ODOO_URL
          value: http://192.168.56.10:30069/
        - name: PGADMIN_URL
          value: http://192.168.56.10:30050/
        ports:
        - containerPort: 8080
          name: ic-webapp
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
