apiVersion: v1
kind: Service
metadata:
  name: ic-webapp-nodeport
  namespace: icgroup
spec:
  selector:
    app: ic-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort
