version: '3.7'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: cGdhZG1pbg==
    volumes:
      - {{ pgadmin_data_dir }}:/var/lib/pgadmin
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    networks:
      - {{ network_name }}

networks:
  {{ network_name }}:
    driver: bridge

volumes:
  {{ pgadmin_data_dir }}:
