apiVersion: v1
kind: Service
metadata:
  name: bdd-odoo-service
  namespace: icgroup
  labels:
    app: bdd-odoo
spec:
  selector:
    app: bdd-odoo
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
